### ISSUE TITLE
Improve Rave Alert Plugin Functionality with Kinsta Caching

### ISSUE THREAD

**Issue by taija** [BellevueCollege/rave-alert-notification#3]
Rave alerts are sometimes not appearing in a timely manner because of overly aggressive caching on the API endpoints that are used to  check for and retrieve alert data. 

This change incorporated a call to Kinsta's cache purge URL to ensure that live data can be fetched and displayed as quickly as possible.

**Comment by efuenzalida52** [comment]
Looks good!
